### ISSUE TITLE
PyPI package is broken

### ISSUE THREAD

**Issue by Techwolfy** [adafruit/Adafruit_CircuitPython_PCF8591#1]
The PyPI package for this library doesn't install any source files.

From a fresh virtualenv:
```
(env) pi@raspberrypi:~ $ pip3 install adafruit-circuitpython-pcf8591
<snip>
Installing collected packages: adafruit-circuitpython-pcf8591
Successfully installed adafruit-circuitpython-pcf8591-1.0.1

(env) pi@raspberrypi:~ $ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import adafruit_pcf8591
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'adafruit_pcf8591'
```

**Comment by tannewt** [comment]
This is usually an issue with the setup.py. In fact, I think this comment explains the change needed: https://github.com/adafruit/Adafruit_CircuitPython_PCF8591/blob/master/setup.py#L60-L62

**Comment by Techwolfy** [comment]
@tannewt Thanks for merging this! Could you please publish a new release to PyPI?

**Comment by ladyada** [comment]
1.0.2 was recenlty published, did you try it?

**Comment by Techwolfy** [comment]
Looks like it was published an hour before my comment; I refreshed the PyPI page before posting, but it still showed the old version then (or the page was cached). The package is working now, thanks again!

**Comment by ladyada** [comment]
rad!
