### ISSUE TITLE
AnalogIn not loading on Ubuntu 22.04.2.LTS

### ISSUE THREAD

**Issue by CAReeser** [adafruit/Adafruit_CircuitPython_PCF8591#9]
Had to downgrade to adafruit-circuitpython-pcf8591-1.0.9.

With adafruit-circuitpython-pcf8591-1.0.15 get following error:
```
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import board
>>> import adafruit_pcf8591.pcf8591 as PCF
>>> from adafruit_pcf8591.analog_in import AnalogIn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/adafruit_pcf8591/analog_in.py", line 37, in <module>
    class AnalogIn:
  File "/usr/local/lib/python3.10/dist-packages/adafruit_pcf8591/analog_in.py", line 40, in AnalogIn
    def __init__(self, pcf: PCF8591, pin: int) -> None:
NameError: name 'PCF8591' is not defined
>>> 

```
Pip3 Freeze:
Adafruit-Blinka==8.19.0
adafruit-circuitpython-bme280==2.6.21
adafruit-circuitpython-busdevice==5.2.5
adafruit-circuitpython-mlx90614==1.2.15
adafruit-circuitpython-pcf8591==1.0.15
adafruit-circuitpython-register==1.9.15
adafruit-circuitpython-requests==1.13.3
adafruit-circuitpython-typing==1.9.3
Adafruit-PlatformDetect==3.46.0
Adafruit-PureIO==1.1.10
aiohttp==3.8.1
aiosignal==1.3.1
aniso8601==9.0.1
astroalign==2.4.1
astroplan==0.8
astropy==5.0
astroquery==0.4.6
async-timeout==4.0.2
asyncio==3.4.3
attrs==21.2.0
Automat==20.2.0
Babel==2.8.0
bcrypt==3.2.0
beautifulsoup4==4.11.1
bidict==0.22.1
blinker==1.4
certifi==2020.6.20
chardet==4.0.0
charset-normalizer==2.1.1
click==8.0.3
cloud-init==23.1.2
colorama==0.4.4
colorzero==2.0
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
contourpy==1.0.7
cryptography==3.4.8
cycler==0.11.0
dbus-python==1.2.18
distro==1.7.0
distro-info===1.1build1
dnspython==2.1.0
dominate==2.7.0
email-validator==1.2.1
eventlet==0.33.1
Flask==2.1.2
Flask-Admin==1.6.0
Flask-Bcrypt==1.0.1
Flask-Bootstrap==3.3.7.1
Flask-Login==0.6.1
Flask-Mail==0.9.1
flask-nav==0.6
flask-restx==0.5.1
Flask-SocketIO==5.2.0
Flask-SQLAlchemy==2.5.1
Flask-WTF==1.0.1
fonttools==4.39.4
frozenlist==1.3.3
gpiozero==1.6.2
greenlet==1.1.2
html5lib==1.1
httplib2==0.20.2
hyperlink==21.0.0
idna==3.3
imageio==2.28.1
importlib-metadata==4.6.4
incremental==21.3.0
itsdangerous==2.0.0
jeepney==0.7.1
Jinja2==3.0.3
jsonpatch==1.32
jsonpointer==2.0
jsonschema==3.2.0
keyring==23.5.0
kiwisolver==1.4.4
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lazy_loader==0.2
lgpio==0.1.0.1
MarkupSafe==2.1.2
matplotlib==3.5.2
metar==1.10.0
more-itertools==8.10.0
multidict==6.0.4
multiprocessing-logging==0.3.3
netifaces==0.11.0
networkx==3.1
numpy==1.21.5
oauthlib==3.2.0
opencv-python==4.6.0.66
packaging==23.1
pandas==1.5.3
pexpect==4.8.0
photutils==1.4.0
Pillow==9.1.1
plotly==5.8.2
psutil==5.9.1
ptyprocess==0.7.0
pyasn1==0.4.8
pyasn1-modules==0.2.1
pyerfa==2.0.0.3
pyftdi==0.54.0
PyGObject==3.42.1
PyHamcrest==2.0.2
PyJWT==2.3.0
pynws==1.4.1
pyOpenSSL==21.0.0
pyparsing==2.4.7
pyrsistent==0.18.1
pyserial==3.5
python-apt==2.4.0+ubuntu1
python-dateutil==2.8.2
python-debian===0.1.43ubuntu1
python-engineio==4.4.1
python-magic==0.4.24
python-socketio==5.8.0
pytz==2022.1
pyusb==1.2.1
pyvo==1.4.1
PyWavelets==1.4.1
PyYAML==5.4.1
requests==2.25.1
RPi.GPIO==0.7.1a4
schedule==1.2.0
scikit-image==0.19.3
scipy==1.8.1
SecretStorage==3.3.1
sep==1.2.1
service-identity==18.1.0
six==1.16.0
sos==4.4
soupsieve==2.4.1
spidev==3.5
SQLAlchemy==1.4.37
ssh-import-id==5.11
systemd-python==234
tenacity==8.2.2
tifffile==2023.4.12
Twisted==22.1.0
typing_extensions==4.5.0
tzdata==2023.3
ubuntu-advantage-tools==8001
ufw==0.36.1
unattended-upgrades==0.1
urllib3==1.26.5
visitor==0.1.3
wadllib==1.3.6
webencodings==0.5.1
Werkzeug==2.1.2
WTForms==3.0.1
yarl==1.9.2
zipp==1.0.0
zope.interface==5.4.0
zwoasi==0.1.0.1

**Comment by tekktrik** [comment]
That's a bug due to incorrect importing of the annotating class.  I can fix that.
